//! Family verdict agreement: check aggregation, impact classification,
//! epoch promotion, change-set transitions, and drift assessment execute
//! identically on every backend.
//!
//! These five corpora were previously generated and committed but never
//! wired to a runner. Each test runs `mncs.family.coherence.v01` against
//! its corpus on every executable backend. (Envelope evaluation —
//! `satisfies` and `evaluate_compatibility` — is covered separately in
//! `family_envelopes.rs`.) All corpora are generated by
//! `scripts/gen-family-coherence-corpora.py`; regeneration is deterministic
//! and committed files must match the generator output.

use std::process::Command;

use serde_json::Value;

fn workspace(name: &str) -> String {
    format!("{}/../../{name}", env!("CARGO_MANIFEST_DIR"))
}

fn library_dir() -> String {
    format!("{}/../../library/", env!("CARGO_MANIFEST_DIR"))
}

const EXECUTABLE_BACKENDS: [&str; 5] = [
    "mncs-research-bytecode",
    "mncs-portable-wasm-mvp",
    "mncs-c11",
    "mncs-llvm-ir",
    "mncs-cranelift",
];

fn run_module_corpus(source: &str, corpus: &str, backend: &str, expected_cases: usize) {
    let output = Command::new(env!("CARGO_BIN_EXE_mncs"))
        .env("MNCS_LIBRARY_PATH", library_dir())
        .args([
            "experiment",
            "run",
            &workspace(source),
            "--backend",
            backend,
            "--corpus",
            &workspace(corpus),
        ])
        .output()
        .expect("run coherence corpus");
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    assert_eq!(
        output.status.code(),
        Some(0),
        "{backend} {source}: exit; {stderr}"
    );
    let result: Value = serde_json::from_slice(&output.stdout)
        .unwrap_or_else(|error| panic!("{backend} {source} JSON ({stderr}): {error}"));
    let cases = result["cases"]
        .as_array()
        .unwrap_or_else(|| panic!("{backend} {source}: missing cases; {result:#}"));
    assert_eq!(
        cases.len(),
        expected_cases,
        "{backend} {source}: corpus drift"
    );
    for case in cases {
        let id = case["case_id"].as_str().unwrap_or("?");
        assert_eq!(
            case["status"], "returned",
            "{backend} {source} {id}: {case:#}"
        );
        assert_eq!(
            case["expectation_met"], true,
            "{backend} {source} {id}: logical value mismatch; returned={:#}",
            case["returned"]
        );
    }
}

#[test]
fn check_aggregation_agrees_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-aggregate-corpus.json",
            backend,
            31,
        );
    }
}

#[test]
fn impact_classification_agrees_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-impact-corpus.json",
            backend,
            16,
        );
    }
}

#[test]
fn epoch_promotion_agrees_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-promotion-corpus.json",
            backend,
            18,
        );
    }
}

#[test]
fn change_set_transitions_agree_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-transition-corpus.json",
            backend,
            72,
        );
    }
}

#[test]
fn drift_assessment_agrees_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-drift-corpus.json",
            backend,
            32,
        );
    }
}
