//! Family verdict agreement: check aggregation, impact classification,
//! epoch promotion, change-set transitions, and drift assessment execute
//! identically on every backend.
//!
//! These five corpora were previously generated and committed but never
//! wired to a runner. Each test runs `mncs.family.coherence.v01` against
//! its corpus on every executable backend. (Envelope evaluation —
//! `satisfies` and `evaluate_compatibility` — is covered separately in
//! `family_envelopes.rs`.) All corpora are generated by
//! `mncs-stdlib/scripts/gen-family-coherence-corpora.py`; regeneration is
//! deterministic and committed files must match the generator output
//! (enforced by the stdlib integrity suite).

use std::process::Command;

use serde_json::Value;

/// Stage F: the `mncs-stdlib` checkout backing these tests: explicit
/// `MNCS_STDLIB_ROOT` wins, else the `mncs-stdlib` sibling checkout.
/// Fails closed with a clear message when absent.
fn stdlib_checkout_dir() -> String {
    // Test inputs need a real checkout: an explicitly empty variable
    // (the CLI's hermetic spelling) falls through to the sibling here.
    let explicit = std::env::var("MNCS_STDLIB_ROOT")
        .ok()
        .filter(|root| !root.trim().is_empty());
    let checkout =
        explicit.unwrap_or_else(|| format!("{}/../../../mncs-stdlib", env!("CARGO_MANIFEST_DIR")));
    assert!(
        std::path::Path::new(&checkout).is_dir(),
        "mncs-stdlib checkout missing at {checkout}; set MNCS_STDLIB_ROOT"
    );
    checkout
}

/// Stage F: standard-library sources now live in `mncs-stdlib/library/`.
fn stdlib_library_dir() -> String {
    let checkout = stdlib_checkout_dir();
    let dir = format!("{checkout}/library");
    assert!(
        std::path::Path::new(&dir).is_dir(),
        "mncs-stdlib checkout missing at {checkout}; set MNCS_STDLIB_ROOT"
    );
    dir
}

fn stdlib_workspace(name: &str) -> String {
    format!("{}/../../../mncs-stdlib/{name}", env!("CARGO_MANIFEST_DIR"))
}

fn library_dir() -> String {
    format!("{}/", stdlib_library_dir())
}

const EXECUTABLE_BACKENDS: [&str; 5] = [
    "mncs-research-bytecode",
    "mncs-portable-wasm-mvp",
    "mncs-c11",
    "mncs-llvm-ir",
    "mncs-cranelift",
];

fn run_module_corpus(source: &str, corpus: &str, backend: &str, expected_cases: usize) {
    let output = Command::new(env!("CARGO_BIN_EXE_mncs"))
        .env("MNCS_LIBRARY_PATH", library_dir())
        .args([
            "experiment",
            "run",
            &stdlib_workspace(source),
            "--backend",
            backend,
            "--corpus",
            &stdlib_workspace(corpus),
        ])
        .output()
        .expect("run coherence corpus");
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    assert_eq!(
        output.status.code(),
        Some(0),
        "{backend} {source}: exit; {stderr}"
    );
    let result: Value = serde_json::from_slice(&output.stdout)
        .unwrap_or_else(|error| panic!("{backend} {source} JSON ({stderr}): {error}"));
    let cases = result["cases"]
        .as_array()
        .unwrap_or_else(|| panic!("{backend} {source}: missing cases; {result:#}"));
    assert_eq!(
        cases.len(),
        expected_cases,
        "{backend} {source}: corpus drift"
    );
    for case in cases {
        let id = case["case_id"].as_str().unwrap_or("?");
        assert_eq!(
            case["status"], "returned",
            "{backend} {source} {id}: {case:#}"
        );
        assert_eq!(
            case["expectation_met"], true,
            "{backend} {source} {id}: logical value mismatch; returned={:#}",
            case["returned"]
        );
    }
}

#[test]
fn check_aggregation_agrees_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-aggregate-corpus.json",
            backend,
            31,
        );
    }
}

#[test]
fn impact_classification_agrees_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-impact-corpus.json",
            backend,
            16,
        );
    }
}

#[test]
fn epoch_promotion_agrees_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-promotion-corpus.json",
            backend,
            18,
        );
    }
}

#[test]
fn change_set_transitions_agree_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-transition-corpus.json",
            backend,
            72,
        );
    }
}

#[test]
fn drift_assessment_agrees_on_every_executable_backend() {
    for backend in EXECUTABLE_BACKENDS {
        run_module_corpus(
            "library/family/coherence.mncs",
            "examples/execution/family-coherence-drift-corpus.json",
            backend,
            32,
        );
    }
}
