//! Language-pressure regression: native soundness across all executable
//! backends. Each workload pins the representation contract that
//! `mncs-math` pressured:
//!
//! - `pressure-f64-arrays`: one coherent `[f64; N]` contract (lengths 2/4/6/8,
//!   locals, params, indexed reads, iteration) with bit-exact IEEE sums,
//!   fractional values, negative zero, large magnitudes, and subnormals.
//! - `pressure-u64-highbit`: unsigned values at/above 2^63 (MAX, 2^63,
//!   2^63+1, neighbors) through checked add/sub, wrapping add, comparisons,
//!   modular `addm`, and `MIN % -1 == 0`.
//! - `pressure-symbol-hygiene`: hostile identifiers (`trunc`, `min`, `exp`)
//!   that must not collide with libc/libm on any native backend.
//!
//! Corpora are generated by `scripts/gen_pressure_corpora.py` from an
//! independent Python oracle (bit-exact floats, exact integers).

use std::process::Command;

use serde_json::Value;

fn example(name: &str) -> String {
    format!("{}/../../examples/{name}", env!("CARGO_MANIFEST_DIR"))
}

fn library(name: &str) -> String {
    format!("{}/../../library/{name}", env!("CARGO_MANIFEST_DIR"))
}

fn binary() -> Command {
    Command::new(env!("CARGO_BIN_EXE_mncs"))
}

fn run_experiment(source: &str, backend: &str, corpus: &str) -> (Option<i32>, Value, String) {
    let output = binary()
        .args([
            "experiment",
            "run",
            source,
            "--backend",
            backend,
            "--corpus",
            corpus,
        ])
        .env("MNCS_LIBRARY_PATH", library(""))
        .output()
        .expect("run experiment");
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    let value: Value = serde_json::from_slice(&output.stdout)
        .unwrap_or_else(|error| panic!("experiment JSON ({stderr}): {error}"));
    (output.status.code(), value, stderr)
}

const EXECUTABLE_BACKENDS: [&str; 5] = [
    "mncs-research-bytecode",
    "mncs-portable-wasm-mvp",
    "mncs-c11",
    "mncs-llvm-ir",
    "mncs-cranelift",
];

fn assert_value_agreement(
    backend: &str,
    code: Option<i32>,
    result: &Value,
    stderr: &str,
    expected_len: usize,
) {
    assert_eq!(
        code,
        Some(0),
        "{backend}: unexpected exit; stderr={stderr}; result={result:#}"
    );
    let cases = result["cases"]
        .as_array()
        .unwrap_or_else(|| panic!("{backend}: missing cases; {result:#}"));
    assert_eq!(
        cases.len(),
        expected_len,
        "{backend}: case count {} != {expected_len}",
        cases.len()
    );
    for case in cases {
        let id = case["case_id"].as_str().unwrap_or("?");
        assert_eq!(
            case["status"], "returned",
            "{backend} {id}: status {:#}",
            case["status"]
        );
        assert_eq!(
            case["expectation_met"], true,
            "{backend} {id}: logical value mismatch; returned={:#}",
            case["returned"]
        );
    }
    let overall = result["status"].as_str().unwrap_or("");
    assert!(
        overall == "PASS" || overall == "UNKNOWN",
        "{backend}: overall status {overall} is not PASS or UNKNOWN"
    );
}

#[test]
fn pressure_f64_arrays_agree_per_backend() {
    let source = example("source/pressure-f64-arrays.mncs");
    let corpus = example("execution/pressure-f64-arrays-corpus.json");
    for backend in EXECUTABLE_BACKENDS {
        let (code, result, stderr) = run_experiment(&source, backend, &corpus);
        assert_value_agreement(backend, code, &result, &stderr, 10);
    }
}

#[test]
fn pressure_f64_records_agree_per_backend() {
    let source = example("source/pressure-f64-records.mncs");
    let corpus = example("execution/pressure-f64-records-corpus.json");
    for backend in EXECUTABLE_BACKENDS {
        let (code, result, stderr) = run_experiment(&source, backend, &corpus);
        assert_value_agreement(backend, code, &result, &stderr, 9);
    }
}

#[test]
fn pressure_u64_highbit_agrees_per_backend() {
    let source = example("source/pressure-u64-highbit.mncs");
    let corpus = example("execution/pressure-u64-highbit-corpus.json");
    for backend in EXECUTABLE_BACKENDS {
        let (code, result, stderr) = run_experiment(&source, backend, &corpus);
        assert_value_agreement(backend, code, &result, &stderr, 9);
    }
}

#[test]
fn pressure_symbol_hygiene_agrees_per_backend() {
    let source = example("source/pressure-symbol-hygiene.mncs");
    let corpus = example("execution/pressure-symbol-hygiene-corpus.json");
    for backend in EXECUTABLE_BACKENDS {
        let (code, result, stderr) = run_experiment(&source, backend, &corpus);
        assert_value_agreement(backend, code, &result, &stderr, 3);
    }
}
