//! Stage C1 float substrate: binary64 arithmetic, comparisons, and
//! conversions on every executable backend. A case is met only when the
//! backend returned the expected logical value with the expected status,
//! not merely when it ran. Trap cases carry no `expected` value: they are
//! met when the backend reports `runtime_failure`.
//!
//! The corpus (`examples/execution/stage-c1-float-corpus.json`) pins the
//! language contract, generated by `scripts/gen_stage_c1_float_corpus.py`
//! from an independent Python (binary64 IEEE) oracle: `+ - * /` and the
//! six comparisons are total over finite values, any non-finite input or
//! result traps (including division by zero, `0.0 / 0.0`, and overflow to
//! infinity), float-to-int truncates toward zero and traps out of domain,
//! and int-to-float rounds per IEEE-754. Expected float values compare as
//! exact bit patterns.

use std::process::Command;

use serde_json::Value;

fn example(name: &str) -> String {
    format!("{}/../../examples/{name}", env!("CARGO_MANIFEST_DIR"))
}

fn library(name: &str) -> String {
    format!("{}/../../library/{name}", env!("CARGO_MANIFEST_DIR"))
}

fn binary() -> Command {
    Command::new(env!("CARGO_BIN_EXE_mncs"))
}

fn run_experiment(source: &str, backend: &str, corpus: &str) -> (Option<i32>, Value, String) {
    let output = binary()
        .args([
            "experiment",
            "run",
            source,
            "--backend",
            backend,
            "--corpus",
            corpus,
        ])
        .env("MNCS_LIBRARY_PATH", library(""))
        .output()
        .expect("run experiment");
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    let value: Value = serde_json::from_slice(&output.stdout)
        .unwrap_or_else(|error| panic!("experiment JSON ({stderr}): {error}"));
    (output.status.code(), value, stderr)
}

const EXECUTABLE_BACKENDS: [&str; 5] = [
    "mncs-research-bytecode",
    "mncs-portable-wasm-mvp",
    "mncs-c11",
    "mncs-llvm-ir",
    "mncs-cranelift",
];

/// Require every case to report the expected status, and every valued
/// case to match the expected logical value bit-for-bit.
fn assert_value_agreement(
    backend: &str,
    code: Option<i32>,
    result: &Value,
    stderr: &str,
    expected_len: usize,
) {
    assert_eq!(
        code,
        Some(0),
        "{backend}: unexpected exit; stderr={stderr}; result={result:#}"
    );
    let cases = result["cases"]
        .as_array()
        .unwrap_or_else(|| panic!("{backend}: missing cases; {result:#}"));
    assert_eq!(
        cases.len(),
        expected_len,
        "{backend}: case count {} != {expected_len}",
        cases.len()
    );
    for case in cases {
        let id = case["case_id"].as_str().unwrap_or("?");
        // Trap cases carry no expected value; their contract is the
        // trap status itself.
        let trap = case
            .get("expected")
            .is_none_or(|expected| expected.is_null());
        let expected_status = if trap { "runtime_failure" } else { "returned" };
        assert_eq!(
            case["status"], expected_status,
            "{backend} {id}: status {:#}",
            case["status"]
        );
        if !case["status_met"].is_null() {
            assert_eq!(
                case["status_met"], true,
                "{backend} {id}: status_met is not true: {case:#}"
            );
        }
        if trap {
            continue;
        }
        assert_eq!(
            case["expectation_met"], true,
            "{backend} {id}: logical value mismatch; returned={:#}",
            case["returned"]
        );
    }
    let overall = result["status"].as_str().unwrap_or("");
    assert!(
        overall == "PASS" || overall == "UNKNOWN",
        "{backend}: overall status {overall} is not PASS or UNKNOWN"
    );
}

#[test]
fn float_arithmetic_agrees_per_backend() {
    let source = example("source/stage-c1-float-arithmetic.mncs");
    let corpus = example("execution/stage-c1-float-corpus.json");
    for backend in EXECUTABLE_BACKENDS {
        let (code, result, stderr) = run_experiment(&source, backend, &corpus);
        assert_value_agreement(backend, code, &result, &stderr, 69);
    }
}
