//! Pinned standard-library bundle (INGEST-P-008).
//!
//! Downstream in-process consumers (for example `mncs-ingest`) need to
//! resolve a pinned `mncs.std.*` identity without depending on the
//! `mncs-language` working-tree path and without copying the library into
//! their own repository. Filesystem roots (`MNCS_LIBRARY_PATH`) remain the
//! development mechanism; the bundle is the distribution mechanism.
//!
//! A bundle is a JSON document carrying every `mncs.*` library module with
//! its source text plus content hashes:
//!
//! - each module records `sha256` over its exact source text;
//! - `bundle_identity` is `mncs:stdlib-bundle:{hex}` over the sorted
//!   `(name, content_sha256)` pairs, so the pin names content, not a path;
//! - loading re-verifies every hash and the bundle identity, failing
//!   closed on any mismatch or duplicate module name.
//!
//! [`StdlibBundle::resolver`] serves the pinned modules through the
//! [`ModuleResolver`](crate::frontend::ModuleResolver) trait, so any
//! `ReferenceCompiler` consumer resolves `mncs.std.chunk.v1` and friends
//! from memory. Name matching is exact and versioned: an unversioned
//! request such as `mncs.std.chunk` never matches the bundle and keeps
//! resolving through the filesystem roots, which preserves the
//! development workflow (working tree wins until the request names a pin).
//! The checked-in pin lives at `library/stdlib-bundle.json`, generated by
//! `mncs bundle generate`; [`PINNED_STDLIB_BUNDLE_JSON`] embeds that same
//! text into every consumer of this crate, so in-process resolution needs
//! no path at all.

use std::collections::BTreeMap;
use std::fmt;

use mncs_syntax::{SourceArtifactKind, SourceEnvelope, SourceOrigin, SourceOriginKind};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::frontend::ModuleResolver;

/// Schema version of the bundle document.
pub const STDLIB_BUNDLE_SCHEMA_VERSION: &str = "mncs.stdlib-bundle/1";

/// The checked-in standard-library pin, generated by
/// `mncs bundle generate` from `library/`. In-process consumers resolve
/// without touching the filesystem through [`pinned_bundle`] and
/// [`StdlibBundle::resolver`].
pub const PINNED_STDLIB_BUNDLE_JSON: &str = include_str!("../../../library/stdlib-bundle.json");

/// One bundled module: pinned name, source text, and addressing metadata.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BundledModule {
    /// Fully versioned module identity, for example `mncs.std.chunk.v1`.
    pub name: String,
    /// Library-relative source path at bundle time, for human auditing.
    pub path: String,
    /// Declared source profile of the module text.
    pub profile: String,
    /// Lowercase hex `sha256` over the exact source text bytes.
    pub content_sha256: String,
    /// The complete module source text.
    pub text: String,
}

/// The bundle document as stored and exchanged.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StdlibBundleManifest {
    pub schema_version: String,
    pub bundle_identity: String,
    pub generator: String,
    pub source_commit: String,
    pub modules: Vec<BundledModule>,
}

/// A verified, queryable bundle.
#[derive(Debug, Clone)]
pub struct StdlibBundle {
    manifest: StdlibBundleManifest,
    texts: BTreeMap<String, String>,
}

/// Loading or verification failure. Always fail closed: a bundle that
/// does not verify byte-for-byte resolves nothing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundleError {
    message: String,
}

impl BundleError {
    fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl fmt::Display for BundleError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "stdlib bundle: {}", self.message)
    }
}

impl std::error::Error for BundleError {}

fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

/// Canonical bundle identity over the sorted `(name, content_sha256)`
/// pairs. The pin names content, never a path or a timestamp.
pub fn bundle_identity_for(modules: &[BundledModule]) -> String {
    let mut ordered: Vec<(&str, &str)> = modules
        .iter()
        .map(|module| (module.name.as_str(), module.content_sha256.as_str()))
        .collect();
    ordered.sort();
    let mut hasher = Sha256::new();
    for (name, digest) in ordered {
        hasher.update(name.as_bytes());
        hasher.update([0u8]);
        hasher.update(digest.as_bytes());
        hasher.update(b"\n");
    }
    format!("mncs:stdlib-bundle:{:x}", hasher.finalize())
}

impl StdlibBundle {
    /// Verify `manifest` byte-for-byte and index it for resolution.
    pub fn from_manifest(manifest: StdlibBundleManifest) -> Result<Self, BundleError> {
        if manifest.schema_version != STDLIB_BUNDLE_SCHEMA_VERSION {
            return Err(BundleError::new(format!(
                "unsupported schema {:?}, expected {:?}",
                manifest.schema_version, STDLIB_BUNDLE_SCHEMA_VERSION
            )));
        }
        let mut texts = BTreeMap::new();
        for module in &manifest.modules {
            if module.name.trim().is_empty() {
                return Err(BundleError::new("bundled module with an empty name"));
            }
            if texts.contains_key(&module.name) {
                return Err(BundleError::new(format!(
                    "duplicate bundled module {:?}",
                    module.name
                )));
            }
            let actual = sha256_hex(module.text.as_bytes());
            if actual != module.content_sha256 {
                return Err(BundleError::new(format!(
                    "content hash mismatch for {:?}: manifest {}, actual {}",
                    module.name, module.content_sha256, actual
                )));
            }
            texts.insert(module.name.clone(), module.text.clone());
        }
        let actual_identity = bundle_identity_for(&manifest.modules);
        if actual_identity != manifest.bundle_identity {
            return Err(BundleError::new(format!(
                "bundle identity mismatch: manifest {}, actual {}",
                manifest.bundle_identity, actual_identity
            )));
        }
        Ok(Self { manifest, texts })
    }

    /// Parse and verify a bundle document.
    pub fn from_json(text: &str) -> Result<Self, BundleError> {
        let manifest: StdlibBundleManifest = serde_json::from_str(text).map_err(|error| {
            BundleError::new(format!("bundle document is not valid JSON: {error}"))
        })?;
        Self::from_manifest(manifest)
    }

    /// Build a bundle from `(name, path, profile, text)` tuples, hashing
    /// every module and sealing the content identity.
    pub fn assemble(
        generator: impl Into<String>,
        source_commit: impl Into<String>,
        modules: Vec<(String, String, String, String)>,
    ) -> Result<Self, BundleError> {
        let mut entries = Vec::with_capacity(modules.len());
        for (name, path, profile, text) in modules {
            entries.push(BundledModule {
                content_sha256: sha256_hex(text.as_bytes()),
                name,
                path,
                profile,
                text,
            });
        }
        let manifest = StdlibBundleManifest {
            schema_version: STDLIB_BUNDLE_SCHEMA_VERSION.to_owned(),
            bundle_identity: bundle_identity_for(&entries),
            generator: generator.into(),
            source_commit: source_commit.into(),
            modules: entries,
        };
        Self::from_manifest(manifest)
    }

    /// Serialize back to the exchange document (canonical JSON shape is
    /// the producer's responsibility; verification is hash-based).
    pub fn to_json_pretty(&self) -> Result<String, BundleError> {
        serde_json::to_string_pretty(&self.manifest)
            .map_err(|error| BundleError::new(format!("bundle serialization failed: {error}")))
    }

    pub fn bundle_identity(&self) -> &str {
        &self.manifest.bundle_identity
    }

    pub fn source_commit(&self) -> &str {
        &self.manifest.source_commit
    }

    /// Sorted pinned module names.
    pub fn module_names(&self) -> Vec<&str> {
        self.texts.keys().map(String::as_str).collect()
    }

    pub fn module_text(&self, name: &str) -> Option<&str> {
        self.texts.get(name).map(String::as_str)
    }

    pub fn len(&self) -> usize {
        self.texts.len()
    }

    pub fn is_empty(&self) -> bool {
        self.texts.is_empty()
    }

    /// A resolver serving exactly the pinned modules. Only exact
    /// versioned names match; everything else (including unversioned
    /// `mncs.*` prefixes) resolves to `None` so filesystem roots keep
    /// serving the development workflow.
    pub fn resolver(&self) -> BundleResolver<'_> {
        BundleResolver { bundle: self }
    }
}

/// [`ModuleResolver`] over a pinned bundle. Envelopes carry a `Generated`
/// origin naming the bundle identity and module, so diagnostics (for
/// example the P-007 import-failure chain) identify the pin that served
/// the source.
#[derive(Debug, Clone, Copy)]
pub struct BundleResolver<'a> {
    bundle: &'a StdlibBundle,
}

impl ModuleResolver for BundleResolver<'_> {
    fn resolve(&self, module: &str) -> Option<SourceEnvelope> {
        let text = self.bundle.module_text(module)?;
        let short = self
            .bundle
            .bundle_identity()
            .rsplit(':')
            .next()
            .unwrap_or("unknown");
        let short: String = short.chars().take(12).collect();
        Some(SourceEnvelope::new(
            SourceArtifactKind::Program,
            module.to_owned(),
            SourceOrigin {
                kind: SourceOriginKind::Generated,
                locator: Some(format!("stdlib-bundle:{short}:{module}")),
            },
            text.to_owned(),
        ))
    }
}

/// The checked-in pin as a verified bundle. Fails when the embedded
/// document drifts from its own hashes (which is exactly the corruption
/// this type exists to catch).
pub fn pinned_bundle() -> Result<StdlibBundle, BundleError> {
    StdlibBundle::from_json(PINNED_STDLIB_BUNDLE_JSON)
}

/// Collect every distributable (`mncs.*`) module under `library_root`
/// for bundling: `(declared name, library-relative path, declared
/// profile, source text)`, sorted by path for deterministic output.
/// Unreadable files and files without a module declaration fail closed;
/// non-`mncs.*` files are skipped (they are not part of the distributed
/// namespace). The declared profile comes from the same inference the
/// source envelope uses, so the bundle never disagrees with the compiler
/// about what a module declares.
pub fn collect_library_modules(
    library_root: &std::path::Path,
) -> Result<Vec<(String, String, String, String)>, BundleError> {
    fn visit(
        directory: &std::path::Path,
        files: &mut Vec<std::path::PathBuf>,
    ) -> Result<(), BundleError> {
        let mut entries: Vec<std::path::PathBuf> = std::fs::read_dir(directory)
            .map_err(|error| {
                BundleError::new(format!(
                    "cannot read library directory {}: {error}",
                    directory.display()
                ))
            })?
            .collect::<Result<Vec<_>, _>>()
            .map_err(|error| {
                BundleError::new(format!(
                    "cannot list library directory {}: {error}",
                    directory.display()
                ))
            })?
            .into_iter()
            .map(|entry| entry.path())
            .collect();
        entries.sort();
        for path in entries {
            if path.is_dir() {
                visit(&path, files)?;
            } else if path
                .extension()
                .is_some_and(|extension| extension == "mncs")
            {
                files.push(path);
            }
        }
        Ok(())
    }

    let mut files = Vec::new();
    visit(library_root, &mut files)?;
    let mut modules = Vec::new();
    for path in files {
        let text = std::fs::read_to_string(&path).map_err(|error| {
            BundleError::new(format!("cannot read {}: {error}", path.display()))
        })?;
        let Some(name) = mncs_syntax::declared_module_name(&text) else {
            return Err(BundleError::new(format!(
                "library file {} declares no module",
                path.display()
            )));
        };
        if !name.starts_with("mncs.") {
            continue;
        }
        let profile =
            SourceEnvelope::inline(SourceArtifactKind::Program, name.clone(), text.clone())
                .language_version;
        let relative = path
            .strip_prefix(library_root)
            .map_err(|_| {
                BundleError::new(format!(
                    "library file {} escapes {}",
                    path.display(),
                    library_root.display()
                ))
            })?
            .components()
            .map(|component| component.as_os_str().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
            .join("/");
        modules.push((name, relative, profile, text));
    }
    Ok(modules)
}
